### ISSUE TITLE
Mlflow 1.9.0 breaks the unit tests

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/fonduer#461]
## Description of the bug

Mlflow 1.9.0 breaks the unit tests.

## To Reproduce
Use mlflow 1.9.0 to run unit tests.

## Expected behavior
Unit tests pass.

## Error Logs/Screenshots
https://github.com/HazyResearch/fonduer/pull/460/checks?check_run_id=791449491

## Environment (please complete the following information)
 - OS: Ubuntu 18.04.4
 - PostgreSQL Version: 12
 - Poppler Utils Version: [e.g. 0.62.0]
 - Fonduer Version: 0.8.2

**Comment by HiromuHota** [comment]
The error log says
```
2020-06-20T21:44:08.6842721Z         # Input both html_path and pdf_html
2020-06-20T21:44:08.6842869Z >       spy = mocker.spy(fonduer_model, "_process")
2020-06-20T21:44:08.6847096Z 
2020-06-20T21:44:08.6847278Z tests/packaging/test_fonduer_model.py:286: 
2020-06-20T21:44:08.6847562Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2020-06-20T21:44:08.6847645Z 
2020-06-20T21:44:08.6850034Z self = <pytest_mock.plugin.MockFixture object at 0x7fceeaabdcf8>
2020-06-20T21:44:08.6850888Z obj = mlflow.pyfunc.loaded_model:
2020-06-20T21:44:08.6851171Z   artifact_path: fonduer_model
2020-06-20T21:44:08.6851402Z   flavor: fonduer.packaging.fonduer_model
2020-06-20T21:44:08.6851536Z   run_id: 69daa63fc90d4ed48155da9a53a3e951
2020-06-20T21:44:08.6851667Z 
2020-06-20T21:44:08.6852147Z name = '_process'
2020-06-20T21:44:08.6852216Z 
2020-06-20T21:44:08.6857084Z     def spy(self, obj, name):
2020-06-20T21:44:08.6860432Z         """
2020-06-20T21:44:08.6863063Z         Creates a spy of method. It will run method normally, but it is now
2020-06-20T21:44:08.6866420Z         possible to use `mock` call features with it, like call count.
2020-06-20T21:44:08.6866609Z     
2020-06-20T21:44:08.6866720Z         :param object obj: An object.
2020-06-20T21:44:08.6868858Z         :param unicode name: A method in object.
2020-06-20T21:44:08.6869029Z         :rtype: mock.MagicMock
2020-06-20T21:44:08.6871943Z         :return: Spy object.
2020-06-20T21:44:08.6872112Z         """
2020-06-20T21:44:08.6872270Z >       method = getattr(obj, name)
2020-06-20T21:44:08.6872798Z E       AttributeError: 'PyFuncModel' object has no attribute '_process'
2020-06-20T21:44:08.6872881Z 
2020-06-20T21:44:08.6876443Z /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/pytest_mock/plugin.py:84: AttributeError
```

I think the change introduced by https://github.com/mlflow/mlflow/pull/2920 is the cause.
As of MLflow v1.9.0, the FonduerModel is wrapped by `PyFuncModel`, which has no attribute '_process'.

**Comment by HiromuHota** [comment]
Another change introduced by mlflow/mlflow#2920 causes another issue.
> Add type enforcement to pyfunc predict. PyFuncModel will enforce input schema for models that contain input signature. The schema enforcement checks column names as well as column types.
